spring.config.import=optional:file:.env[.properties]
spring.application.name=SR_GROUP_02_SPRING_MINI_PROJECT
server.port=9090

spring.datasource.url=${POSTGRES_DB_URL}${POSTGRES_DB_NAME}
spring.datasource.username=${POSTGRES_DB_USERNAME}
spring.datasource.password=${POSTGRES_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB

rustfs.url=${RUSTFS_URL}
rustfs.access.name=${RUSTFS_ACCESS_KEY}
rustfs.access.secret=${RUSTFS_SECRET_KEY}
rustfs.bucket.name=${RUSTFS_BUCKET_NAME}